// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFEgWDMvOwJcxIF_D0ZlWSPmZ_EnMhDQE',
    appId: '1:791947403395:web:616319ecdb5f6c2b40fbb6',
    messagingSenderId: '791947403395',
    projectId: 'comfystay-f02ed',
    authDomain: 'comfystay-f02ed.firebaseapp.com',
    storageBucket: 'comfystay-f02ed.appspot.com',
    measurementId: 'G-8CR8D0F029',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoJ-MhKq3PNzfagfzXuRfHOHA0_Tfd_Ss',
    appId: '1:1013003120098:android:c106fb48df59356c32ddbb',
    messagingSenderId: '1013003120098',
    projectId: 'comfy-stay-fdfd0',
    storageBucket: 'comfy-stay-fdfd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxZ001Azpzx0Irvs4asao65WY7LVT46F0',
    appId: '1:1013003120098:ios:80e9f07a0bfe2c7a32ddbb',
    messagingSenderId: '1013003120098',
    projectId: 'comfy-stay-fdfd0',
    storageBucket: 'comfy-stay-fdfd0.firebasestorage.app',
    iosBundleId: 'com.example.comfystay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLLJnW7TvBxq70vfyOErZVhyvjG5WQiUE',
    appId: '1:791947403395:ios:36cff8afb939b34840fbb6',
    messagingSenderId: '791947403395',
    projectId: 'comfystay-f02ed',
    storageBucket: 'comfystay-f02ed.appspot.com',
    iosBundleId: 'com.example.comfystay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFEgWDMvOwJcxIF_D0ZlWSPmZ_EnMhDQE',
    appId: '1:791947403395:web:96b4a1868984b8b440fbb6',
    messagingSenderId: '791947403395',
    projectId: 'comfystay-f02ed',
    authDomain: 'comfystay-f02ed.firebaseapp.com',
    storageBucket: 'comfystay-f02ed.appspot.com',
    measurementId: 'G-25SXKV1VNM',
  );
}